'''
Import('env_vmm')
vmm = env_vmm.Program('vmm',Glob('source/*.c'))
install_bin = env_vmm.Install('$BIN_DIR', vmm)

Default([vmm, install_bin])
'''

Import('env')

my_env = env.Clone(LIBPATH='', LIBS='')
#d = my_env.ParseFlags('-lzmq  -lpthread')
#my_env.MergeFlags(d)

wtd = my_env.Program('wtd',Glob('source/*.c'))
install_bin = my_env.Install('$BIN_DIR', wtd)

Default([wtd, install_bin])
