/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_config (cparser_t *parser)
{
    cparser_cmd_config(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_exit (cparser_t *parser)
{
    cparser_cmd_config_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_get_key (cparser_t *parser)
{
    char *key_val;
    char **key_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &key_val);
    assert(CPARSER_OK == rc);
    key_ptr = &key_val;
    cparser_cmd_config_get_key(&parser->context,
        key_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_set_key_value (cparser_t *parser)
{
    char *key_val;
    char **key_ptr = NULL;
    char *value_val;
    char **value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &key_val);
    assert(CPARSER_OK == rc);
    key_ptr = &key_val;
    rc = cparser_get_string(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_config_set_key_value(&parser->context,
        key_ptr,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_save (cparser_t *parser)
{
    cparser_cmd_config_save(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_restore (cparser_t *parser)
{
    cparser_cmd_config_restore(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_reset (cparser_t *parser)
{
    cparser_cmd_config_reset(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_config_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version (cparser_t *parser)
{
    cparser_cmd_version(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version_exit (cparser_t *parser)
{
    cparser_cmd_version_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord (cparser_t *parser)
{
    char *ServerType_val;
    char **ServerType_ptr = NULL;
    char *VersionType_val;
    char **VersionType_ptr = NULL;
    char *VersionName_val;
    char **VersionName_ptr = NULL;
    uint32_t ServerIP_val;
    uint32_t *ServerIP_ptr = NULL;
    uint32_t Port_val;
    uint32_t *Port_ptr = NULL;
    char *UserName_val;
    char **UserName_ptr = NULL;
    char *PassWord_val;
    char **PassWord_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[2], &ServerType_val);
    assert(CPARSER_OK == rc);
    ServerType_ptr = &ServerType_val;
    rc = cparser_get_list(&parser->tokens[3], &VersionType_val);
    assert(CPARSER_OK == rc);
    VersionType_ptr = &VersionType_val;
    rc = cparser_get_string(&parser->tokens[4], &VersionName_val);
    assert(CPARSER_OK == rc);
    VersionName_ptr = &VersionName_val;
    rc = cparser_get_ipv4addr(&parser->tokens[5], &ServerIP_val);
    assert(CPARSER_OK == rc);
    ServerIP_ptr = &ServerIP_val;
    rc = cparser_get_uint(&parser->tokens[6], &Port_val);
    assert(CPARSER_OK == rc);
    Port_ptr = &Port_val;
    rc = cparser_get_string(&parser->tokens[7], &UserName_val);
    if (CPARSER_OK == rc) {
        UserName_ptr = &UserName_val;
    } else {
        assert(8 > parser->token_tos);
    }
    rc = cparser_get_string(&parser->tokens[8], &PassWord_val);
    if (CPARSER_OK == rc) {
        PassWord_ptr = &PassWord_val;
    } else {
        assert(9 > parser->token_tos);
    }
    cparser_cmd_version_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord(&parser->context,
        ServerType_ptr,
        VersionType_ptr,
        VersionName_ptr,
        ServerIP_ptr,
        Port_ptr,
        UserName_ptr,
        PassWord_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version_query (cparser_t *parser)
{
    cparser_cmd_version_query(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version_switch (cparser_t *parser)
{
    cparser_cmd_version_switch(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version_unswitch (cparser_t *parser)
{
    cparser_cmd_version_unswitch(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_version_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_version_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_diagnose (cparser_t *parser)
{
    cparser_cmd_diagnose(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest (cparser_t *parser)
{
    cparser_cmd_drvtest(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_exit (cparser_t *parser)
{
    cparser_cmd_drvtest_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_norflash_mod_offset_len_data (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t len_val;
    uint32_t *len_ptr = NULL;
    uint32_t data_val;
    uint32_t *data_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_hex(&parser->tokens[2], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_hex(&parser->tokens[3], &len_val);
    assert(CPARSER_OK == rc);
    len_ptr = &len_val;
    rc = cparser_get_hex(&parser->tokens[4], &data_val);
    assert(CPARSER_OK == rc);
    data_ptr = &data_val;
    cparser_cmd_drvtest_norflash_mod_offset_len_data(&parser->context,
        mod_ptr,
        offset_ptr,
        len_ptr,
        data_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_epld_mod_addr_data (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    uint32_t addr_val;
    uint32_t *addr_ptr = NULL;
    uint32_t data_val;
    uint32_t *data_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_hex(&parser->tokens[2], &addr_val);
    assert(CPARSER_OK == rc);
    addr_ptr = &addr_val;
    rc = cparser_get_hex(&parser->tokens[3], &data_val);
    assert(CPARSER_OK == rc);
    data_ptr = &data_val;
    cparser_cmd_drvtest_epld_mod_addr_data(&parser->context,
        mod_ptr,
        addr_ptr,
        data_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_eeprom_mod_data (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    uint32_t data_val;
    uint32_t *data_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_hex(&parser->tokens[2], &data_val);
    assert(CPARSER_OK == rc);
    data_ptr = &data_val;
    cparser_cmd_drvtest_eeprom_mod_data(&parser->context,
        mod_ptr,
        data_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_eepromaddr_mod_addr_len_data (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    uint32_t addr_val;
    uint32_t *addr_ptr = NULL;
    uint32_t len_val;
    uint32_t *len_ptr = NULL;
    char *data_val;
    char **data_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_uint(&parser->tokens[2], &addr_val);
    assert(CPARSER_OK == rc);
    addr_ptr = &addr_val;
    rc = cparser_get_uint(&parser->tokens[3], &len_val);
    assert(CPARSER_OK == rc);
    len_ptr = &len_val;
    rc = cparser_get_string(&parser->tokens[4], &data_val);
    if (CPARSER_OK == rc) {
        data_ptr = &data_val;
    } else {
        assert(5 > parser->token_tos);
    }
    cparser_cmd_drvtest_eepromaddr_mod_addr_len_data(&parser->context,
        mod_ptr,
        addr_ptr,
        len_ptr,
        data_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_seteeprom_configPath (cparser_t *parser)
{
    char *configPath_val;
    char **configPath_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &configPath_val);
    assert(CPARSER_OK == rc);
    configPath_ptr = &configPath_val;
    cparser_cmd_drvtest_seteeprom_configPath(&parser->context,
        configPath_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_uart_index_baundrate_testMode_loopNum (cparser_t *parser)
{
    int32_t index_val;
    int32_t *index_ptr = NULL;
    int32_t baundrate_val;
    int32_t *baundrate_ptr = NULL;
    char *testMode_val;
    char **testMode_ptr = NULL;
    int32_t loopNum_val;
    int32_t *loopNum_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[1], &index_val);
    assert(CPARSER_OK == rc);
    index_ptr = &index_val;
    rc = cparser_get_int(&parser->tokens[2], &baundrate_val);
    assert(CPARSER_OK == rc);
    baundrate_ptr = &baundrate_val;
    rc = cparser_get_string(&parser->tokens[3], &testMode_val);
    assert(CPARSER_OK == rc);
    testMode_ptr = &testMode_val;
    rc = cparser_get_int(&parser->tokens[4], &loopNum_val);
    assert(CPARSER_OK == rc);
    loopNum_ptr = &loopNum_val;
    cparser_cmd_drvtest_uart_index_baundrate_testMode_loopNum(&parser->context,
        index_ptr,
        baundrate_ptr,
        testMode_ptr,
        loopNum_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_wtd_wtd_mod (cparser_t *parser)
{
    char *wtd_mod_val;
    char **wtd_mod_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &wtd_mod_val);
    assert(CPARSER_OK == rc);
    wtd_mod_ptr = &wtd_mod_val;
    cparser_cmd_drvtest_wtd_wtd_mod(&parser->context,
        wtd_mod_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_psam_pasm_mod_VALUE (cparser_t *parser)
{
    char *pasm_mod_val;
    char **pasm_mod_ptr = NULL;
    int32_t VALUE_val;
    int32_t *VALUE_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &pasm_mod_val);
    assert(CPARSER_OK == rc);
    pasm_mod_ptr = &pasm_mod_val;
    rc = cparser_get_int(&parser->tokens[2], &VALUE_val);
    assert(CPARSER_OK == rc);
    VALUE_ptr = &VALUE_val;
    cparser_cmd_drvtest_psam_pasm_mod_VALUE(&parser->context,
        pasm_mod_ptr,
        VALUE_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_loadfpga_verPath (cparser_t *parser)
{
    char *verPath_val;
    char **verPath_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &verPath_val);
    assert(CPARSER_OK == rc);
    verPath_ptr = &verPath_val;
    cparser_cmd_drvtest_loadfpga_verPath(&parser->context,
        verPath_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_fpga_mod_addr_data (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    uint32_t addr_val;
    uint32_t *addr_ptr = NULL;
    uint32_t data_val;
    uint32_t *data_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_hex(&parser->tokens[2], &addr_val);
    assert(CPARSER_OK == rc);
    addr_ptr = &addr_val;
    rc = cparser_get_hex(&parser->tokens[3], &data_val);
    assert(CPARSER_OK == rc);
    data_ptr = &data_val;
    cparser_cmd_drvtest_fpga_mod_addr_data(&parser->context,
        mod_ptr,
        addr_ptr,
        data_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_lcd_mod (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    cparser_cmd_drvtest_lcd_mod(&parser->context,
        mod_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_led_mod_state (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    int32_t state_val;
    int32_t *state_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_int(&parser->tokens[2], &state_val);
    assert(CPARSER_OK == rc);
    state_ptr = &state_val;
    cparser_cmd_drvtest_led_mod_state(&parser->context,
        mod_ptr,
        state_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_devicectl_mod_devlist_powctl (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    int32_t devlist_val;
    int32_t *devlist_ptr = NULL;
    int32_t powctl_val;
    int32_t *powctl_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_int(&parser->tokens[2], &devlist_val);
    assert(CPARSER_OK == rc);
    devlist_ptr = &devlist_val;
    rc = cparser_get_int(&parser->tokens[3], &powctl_val);
    assert(CPARSER_OK == rc);
    powctl_ptr = &powctl_val;
    cparser_cmd_drvtest_devicectl_mod_devlist_powctl(&parser->context,
        mod_ptr,
        devlist_ptr,
        powctl_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_key (cparser_t *parser)
{
    cparser_cmd_drvtest_key(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_ver (cparser_t *parser)
{
    cparser_cmd_drvtest_ver(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_rtcset_year_mon_mon_day_week_day_hour_min_sec (cparser_t *parser)
{
    int32_t year_val;
    int32_t *year_ptr = NULL;
    int32_t mon_val;
    int32_t *mon_ptr = NULL;
    int32_t mon_day_val;
    int32_t *mon_day_ptr = NULL;
    int32_t week_day_val;
    int32_t *week_day_ptr = NULL;
    int32_t hour_val;
    int32_t *hour_ptr = NULL;
    int32_t min_val;
    int32_t *min_ptr = NULL;
    int32_t sec_val;
    int32_t *sec_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[1], &year_val);
    assert(CPARSER_OK == rc);
    year_ptr = &year_val;
    rc = cparser_get_int(&parser->tokens[2], &mon_val);
    assert(CPARSER_OK == rc);
    mon_ptr = &mon_val;
    rc = cparser_get_int(&parser->tokens[3], &mon_day_val);
    assert(CPARSER_OK == rc);
    mon_day_ptr = &mon_day_val;
    rc = cparser_get_int(&parser->tokens[4], &week_day_val);
    assert(CPARSER_OK == rc);
    week_day_ptr = &week_day_val;
    rc = cparser_get_int(&parser->tokens[5], &hour_val);
    assert(CPARSER_OK == rc);
    hour_ptr = &hour_val;
    rc = cparser_get_int(&parser->tokens[6], &min_val);
    assert(CPARSER_OK == rc);
    min_ptr = &min_val;
    rc = cparser_get_int(&parser->tokens[7], &sec_val);
    assert(CPARSER_OK == rc);
    sec_ptr = &sec_val;
    cparser_cmd_drvtest_rtcset_year_mon_mon_day_week_day_hour_min_sec(&parser->context,
        year_ptr,
        mon_ptr,
        mon_day_ptr,
        week_day_ptr,
        hour_ptr,
        min_ptr,
        sec_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_rtcget (cparser_t *parser)
{
    cparser_cmd_drvtest_rtcget(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_tsentor_mod_id_temper (cparser_t *parser)
{
    char *mod_val;
    char **mod_ptr = NULL;
    int32_t id_val;
    int32_t *id_ptr = NULL;
    int32_t temper_val;
    int32_t *temper_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &mod_val);
    assert(CPARSER_OK == rc);
    mod_ptr = &mod_val;
    rc = cparser_get_int(&parser->tokens[2], &id_val);
    assert(CPARSER_OK == rc);
    id_ptr = &id_val;
    rc = cparser_get_int(&parser->tokens[3], &temper_val);
    assert(CPARSER_OK == rc);
    temper_ptr = &temper_val;
    cparser_cmd_drvtest_tsentor_mod_id_temper(&parser->context,
        mod_ptr,
        id_ptr,
        temper_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_net_loopNum (cparser_t *parser)
{
    int32_t loopNum_val;
    int32_t *loopNum_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[1], &loopNum_val);
    assert(CPARSER_OK == rc);
    loopNum_ptr = &loopNum_val;
    cparser_cmd_drvtest_net_loopNum(&parser->context,
        loopNum_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_drvtest_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_drvtest_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_quit (cparser_t *parser)
{
    cparser_cmd_quit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_quit,
    "Leave the database",
    NULL,
    NULL
};

cparser_node_t cparser_node_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    NULL,
    NULL,
    &cparser_node_quit_eol
};

cparser_node_t cparser_node_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};

cparser_node_t cparser_node_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_help_filter_eol
};

cparser_node_t cparser_node_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_help_filter,
    NULL,
    &cparser_node_help_filter,
    NULL
};

cparser_node_t cparser_node_help = {
    CPARSER_NODE_KEYWORD,
    0,
    "help",
    NULL,
    &cparser_node_quit,
    &cparser_node_help_eol
};

cparser_node_t cparser_node_drvtest_root_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_help_filter_eol
};

cparser_node_t cparser_node_drvtest_root_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_drvtest_help_filter,
    NULL,
    &cparser_node_drvtest_root_help_filter,
    NULL
};

cparser_node_t cparser_node_drvtest_root_help = {
    CPARSER_NODE_KEYWORD,
    0,
    "help",
    NULL,
    NULL,
    &cparser_node_drvtest_root_help_eol
};

cparser_node_t cparser_node_drvtest_root_net_loopNum_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_net_loopNum,
    "test net,loopNum:loopNum>0 ",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_net_loopNum = {
    CPARSER_NODE_INT,
    0,
    "<INT:loopNum>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_net_loopNum_eol
};

cparser_node_t cparser_node_drvtest_root_net = {
    CPARSER_NODE_KEYWORD,
    0,
    "net",
    NULL,
    &cparser_node_drvtest_root_help,
    &cparser_node_drvtest_root_net_loopNum
};

cparser_node_t cparser_node_drvtest_root_tsentor_mod_id_temper_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_tsentor_mod_id_temper,
    "test tsentor,mode:set,get;id:0-6;temper:set temperature value",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_tsentor_mod_id_temper = {
    CPARSER_NODE_INT,
    0,
    "<INT:temper>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_tsentor_mod_id_temper_eol
};

cparser_node_t cparser_node_drvtest_root_tsentor_mod_id = {
    CPARSER_NODE_INT,
    0,
    "<INT:id>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_tsentor_mod_id_temper
};

cparser_node_t cparser_node_drvtest_root_tsentor_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_tsentor_mod_id
};

cparser_node_t cparser_node_drvtest_root_tsentor = {
    CPARSER_NODE_KEYWORD,
    0,
    "tsentor",
    NULL,
    &cparser_node_drvtest_root_net,
    &cparser_node_drvtest_root_tsentor_mod
};

cparser_node_t cparser_node_drvtest_root_rtcget_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_rtcget,
    "get rtc",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_rtcget = {
    CPARSER_NODE_KEYWORD,
    0,
    "rtcget",
    NULL,
    &cparser_node_drvtest_root_tsentor,
    &cparser_node_drvtest_root_rtcget_eol
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour_min_sec_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_rtcset_year_mon_mon_day_week_day_hour_min_sec,
    "set rtc",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour_min_sec = {
    CPARSER_NODE_INT,
    0,
    "<INT:sec>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour_min_sec_eol
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour_min = {
    CPARSER_NODE_INT,
    0,
    "<INT:min>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour_min_sec
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour = {
    CPARSER_NODE_INT,
    0,
    "<INT:hour>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour_min
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day = {
    CPARSER_NODE_INT,
    0,
    "<INT:week_day>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day_hour
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon_mon_day = {
    CPARSER_NODE_INT,
    0,
    "<INT:mon_day>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon_mon_day_week_day
};

cparser_node_t cparser_node_drvtest_root_rtcset_year_mon = {
    CPARSER_NODE_INT,
    0,
    "<INT:mon>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon_mon_day
};

cparser_node_t cparser_node_drvtest_root_rtcset_year = {
    CPARSER_NODE_INT,
    0,
    "<INT:year>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_rtcset_year_mon
};

cparser_node_t cparser_node_drvtest_root_rtcset = {
    CPARSER_NODE_KEYWORD,
    0,
    "rtcset",
    NULL,
    &cparser_node_drvtest_root_rtcget,
    &cparser_node_drvtest_root_rtcset_year
};

cparser_node_t cparser_node_drvtest_root_ver_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_ver,
    "test veriche",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_ver = {
    CPARSER_NODE_KEYWORD,
    0,
    "ver",
    NULL,
    &cparser_node_drvtest_root_rtcset,
    &cparser_node_drvtest_root_ver_eol
};

cparser_node_t cparser_node_drvtest_root_key_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_key,
    "test key,input key",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_key = {
    CPARSER_NODE_KEYWORD,
    0,
    "key",
    NULL,
    &cparser_node_drvtest_root_ver,
    &cparser_node_drvtest_root_key_eol
};

cparser_node_t cparser_node_drvtest_root_devicectl_mod_devlist_powctl_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_devicectl_mod_devlist_powctl,
    "test devicectl ,mode:rst,pow;devlist:rst mode:(usb:0,752:1,eth2:2,eth1:3);pow mod:(rf:0,sd:1,oled:2,usb:3,psam0~3:4~7);powctl:0:off;1:on.",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_devicectl_mod_devlist_powctl = {
    CPARSER_NODE_INT,
    0,
    "<INT:powctl>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_devicectl_mod_devlist_powctl_eol
};

cparser_node_t cparser_node_drvtest_root_devicectl_mod_devlist = {
    CPARSER_NODE_INT,
    0,
    "<INT:devlist>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_devicectl_mod_devlist_powctl
};

cparser_node_t cparser_node_drvtest_root_devicectl_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_devicectl_mod_devlist
};

cparser_node_t cparser_node_drvtest_root_devicectl = {
    CPARSER_NODE_KEYWORD,
    0,
    "devicectl",
    NULL,
    &cparser_node_drvtest_root_key,
    &cparser_node_drvtest_root_devicectl_mod
};

cparser_node_t cparser_node_drvtest_root_led_mod_state_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_led_mod_state,
    "test led ,mode:run,pasm;alarm.state:0:off;1:on.",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_led_mod_state = {
    CPARSER_NODE_INT,
    0,
    "<INT:state>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_led_mod_state_eol
};

cparser_node_t cparser_node_drvtest_root_led_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_led_mod_state
};

cparser_node_t cparser_node_drvtest_root_led = {
    CPARSER_NODE_KEYWORD,
    0,
    "led",
    NULL,
    &cparser_node_drvtest_root_devicectl,
    &cparser_node_drvtest_root_led_mod
};

cparser_node_t cparser_node_drvtest_root_lcd_mod_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_lcd_mod,
    "test lcd ,mode:clear,light;showstr",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_lcd_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_lcd_mod_eol
};

cparser_node_t cparser_node_drvtest_root_lcd = {
    CPARSER_NODE_KEYWORD,
    0,
    "lcd",
    NULL,
    &cparser_node_drvtest_root_led,
    &cparser_node_drvtest_root_lcd_mod
};

cparser_node_t cparser_node_drvtest_root_fpga_mod_addr_data_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_fpga_mod_addr_data,
    "test fpga ,mode:write,read;addr:fpga reg address;data:input 16bit HEX data.",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_fpga_mod_addr_data = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:data>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_fpga_mod_addr_data_eol
};

cparser_node_t cparser_node_drvtest_root_fpga_mod_addr = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:addr>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_fpga_mod_addr_data
};

cparser_node_t cparser_node_drvtest_root_fpga_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_fpga_mod_addr
};

cparser_node_t cparser_node_drvtest_root_fpga = {
    CPARSER_NODE_KEYWORD,
    0,
    "fpga",
    NULL,
    &cparser_node_drvtest_root_lcd,
    &cparser_node_drvtest_root_fpga_mod
};

cparser_node_t cparser_node_drvtest_root_loadfpga_verPath_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_loadfpga_verPath,
    "test load fpga version.verPath:version file path.",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_loadfpga_verPath = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:verPath>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_loadfpga_verPath_eol
};

cparser_node_t cparser_node_drvtest_root_loadfpga = {
    CPARSER_NODE_KEYWORD,
    0,
    "loadfpga",
    NULL,
    &cparser_node_drvtest_root_fpga,
    &cparser_node_drvtest_root_loadfpga_verPath
};

cparser_node_t cparser_node_drvtest_root_psam_pasm_mod_VALUE_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_psam_pasm_mod_VALUE,
    "test psam. pasm_mod:init,setclk,active,deactive,getrand,choseapp,getkey,decryptinfo,decrypt,enablepps,disablepps;VALUE:init mode:invalid,setclk mode :divclk,other:CardId(0~3);",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_psam_pasm_mod_VALUE = {
    CPARSER_NODE_INT,
    0,
    "<INT:VALUE>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_psam_pasm_mod_VALUE_eol
};

cparser_node_t cparser_node_drvtest_root_psam_pasm_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:pasm_mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_psam_pasm_mod_VALUE
};

cparser_node_t cparser_node_drvtest_root_psam = {
    CPARSER_NODE_KEYWORD,
    0,
    "psam",
    NULL,
    &cparser_node_drvtest_root_loadfpga,
    &cparser_node_drvtest_root_psam_pasm_mod
};

cparser_node_t cparser_node_drvtest_root_wtd_wtd_mod_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_wtd_wtd_mod,
    "test watch dog.wtd_mod:softWtd,hwWtd,stopWtd;",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_wtd_wtd_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:wtd_mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_wtd_wtd_mod_eol
};

cparser_node_t cparser_node_drvtest_root_wtd = {
    CPARSER_NODE_KEYWORD,
    0,
    "wtd",
    NULL,
    &cparser_node_drvtest_root_psam,
    &cparser_node_drvtest_root_wtd_wtd_mod
};

cparser_node_t cparser_node_drvtest_root_uart_index_baundrate_testMode_loopNum_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_uart_index_baundrate_testMode_loopNum,
    "test uart. index:0,1,2; baundrate:115200,9600...; testMode:rec_send,loopback; loopNum:loopNum>0",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_uart_index_baundrate_testMode_loopNum = {
    CPARSER_NODE_INT,
    0,
    "<INT:loopNum>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_uart_index_baundrate_testMode_loopNum_eol
};

cparser_node_t cparser_node_drvtest_root_uart_index_baundrate_testMode = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:testMode>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_uart_index_baundrate_testMode_loopNum
};

cparser_node_t cparser_node_drvtest_root_uart_index_baundrate = {
    CPARSER_NODE_INT,
    0,
    "<INT:baundrate>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_uart_index_baundrate_testMode
};

cparser_node_t cparser_node_drvtest_root_uart_index = {
    CPARSER_NODE_INT,
    0,
    "<INT:index>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_uart_index_baundrate
};

cparser_node_t cparser_node_drvtest_root_uart = {
    CPARSER_NODE_KEYWORD,
    0,
    "uart",
    NULL,
    &cparser_node_drvtest_root_wtd,
    &cparser_node_drvtest_root_uart_index
};

cparser_node_t cparser_node_drvtest_root_seteeprom_configPath_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_seteeprom_configPath,
    "seteeprom,configPath:config file path",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_seteeprom_configPath = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:configPath>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_seteeprom_configPath_eol
};

cparser_node_t cparser_node_drvtest_root_seteeprom = {
    CPARSER_NODE_KEYWORD,
    0,
    "seteeprom",
    NULL,
    &cparser_node_drvtest_root_uart,
    &cparser_node_drvtest_root_seteeprom_configPath
};

cparser_node_t cparser_node_drvtest_root_eepromaddr_mod_addr_len_data_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_eepromaddr_mod_addr_len_data,
    "test eeprom,mode:write,read",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_eepromaddr_mod_addr_len_data = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:data>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_eepromaddr_mod_addr_len_data_eol
};

cparser_node_t cparser_node_drvtest_root_eepromaddr_mod_addr_len_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_drvtest_eepromaddr_mod_addr_len_data,
    NULL,
    &cparser_node_drvtest_root_eepromaddr_mod_addr_len_data,
    NULL
};

cparser_node_t cparser_node_drvtest_root_eepromaddr_mod_addr_len = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:len>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_eepromaddr_mod_addr_len_eol
};

cparser_node_t cparser_node_drvtest_root_eepromaddr_mod_addr = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:addr>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_eepromaddr_mod_addr_len
};

cparser_node_t cparser_node_drvtest_root_eepromaddr_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_eepromaddr_mod_addr
};

cparser_node_t cparser_node_drvtest_root_eepromaddr = {
    CPARSER_NODE_KEYWORD,
    0,
    "eepromaddr",
    NULL,
    &cparser_node_drvtest_root_seteeprom,
    &cparser_node_drvtest_root_eepromaddr_mod
};

cparser_node_t cparser_node_drvtest_root_eeprom_mod_data_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_eeprom_mod_data,
    "test eeprom,mode:save,write,read,recover",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_eeprom_mod_data = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:data>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_eeprom_mod_data_eol
};

cparser_node_t cparser_node_drvtest_root_eeprom_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_eeprom_mod_data
};

cparser_node_t cparser_node_drvtest_root_eeprom = {
    CPARSER_NODE_KEYWORD,
    0,
    "eeprom",
    NULL,
    &cparser_node_drvtest_root_eepromaddr,
    &cparser_node_drvtest_root_eeprom_mod
};

cparser_node_t cparser_node_drvtest_root_epld_mod_addr_data_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_epld_mod_addr_data,
    "test epld ,mode:write,read;addr:epld reg address;data:input 16bit HEX data.",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_epld_mod_addr_data = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:data>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_epld_mod_addr_data_eol
};

cparser_node_t cparser_node_drvtest_root_epld_mod_addr = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:addr>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_epld_mod_addr_data
};

cparser_node_t cparser_node_drvtest_root_epld_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_epld_mod_addr
};

cparser_node_t cparser_node_drvtest_root_epld = {
    CPARSER_NODE_KEYWORD,
    0,
    "epld",
    NULL,
    &cparser_node_drvtest_root_eeprom,
    &cparser_node_drvtest_root_epld_mod
};

cparser_node_t cparser_node_drvtest_root_norflash_mod_offset_len_data_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_norflash_mod_offset_len_data,
    "test norflash, mod:write,read,erase,info;offset:offset>0x3c00000;len:len<0x40000;data:write data",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_norflash_mod_offset_len_data = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:data>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_norflash_mod_offset_len_data_eol
};

cparser_node_t cparser_node_drvtest_root_norflash_mod_offset_len = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:len>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_norflash_mod_offset_len_data
};

cparser_node_t cparser_node_drvtest_root_norflash_mod_offset = {
    CPARSER_NODE_HEX,
    0,
    "<HEX:offset>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_norflash_mod_offset_len
};

cparser_node_t cparser_node_drvtest_root_norflash_mod = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:mod>",
    NULL,
    NULL,
    &cparser_node_drvtest_root_norflash_mod_offset
};

cparser_node_t cparser_node_drvtest_root_norflash = {
    CPARSER_NODE_KEYWORD,
    0,
    "norflash",
    NULL,
    &cparser_node_drvtest_root_epld,
    &cparser_node_drvtest_root_norflash_mod
};

cparser_node_t cparser_node_drvtest_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest_exit,
    "Exit drvtest submode",
    NULL,
    NULL
};

cparser_node_t cparser_node_drvtest_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    &cparser_node_drvtest_root_norflash,
    &cparser_node_drvtest_root_exit_eol
};

cparser_node_t cparser_node_drvtest_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode drvtest",
    NULL,
    &cparser_node_drvtest_root_exit
};

cparser_node_t cparser_node_drvtest_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_drvtest,
    "driver test",
    NULL,
    &cparser_node_drvtest_root
};

cparser_node_t cparser_node_drvtest = {
    CPARSER_NODE_KEYWORD,
    0,
    "drvtest",
    NULL,
    &cparser_node_help,
    &cparser_node_drvtest_eol
};

cparser_node_t cparser_node_diagnose_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_diagnose,
    "diagnose",
    NULL,
    NULL
};

cparser_node_t cparser_node_diagnose = {
    CPARSER_NODE_KEYWORD,
    0,
    "diagnose",
    NULL,
    &cparser_node_drvtest,
    &cparser_node_diagnose_eol
};

cparser_node_t cparser_node_version_root_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};

cparser_node_t cparser_node_version_root_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_version_root_help_filter_eol
};

cparser_node_t cparser_node_version_root_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_version_help_filter,
    NULL,
    &cparser_node_version_root_help_filter,
    NULL
};

cparser_node_t cparser_node_version_root_help = {
    CPARSER_NODE_KEYWORD,
    0,
    "help",
    NULL,
    NULL,
    &cparser_node_version_root_help_eol
};

cparser_node_t cparser_node_version_root_unswitch_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version_unswitch,
    "unswitch version",
    NULL,
    NULL
};

cparser_node_t cparser_node_version_root_unswitch = {
    CPARSER_NODE_KEYWORD,
    0,
    "unswitch",
    NULL,
    &cparser_node_version_root_help,
    &cparser_node_version_root_unswitch_eol
};

cparser_node_t cparser_node_version_root_switch_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version_switch,
    "switch version",
    NULL,
    NULL
};

cparser_node_t cparser_node_version_root_switch = {
    CPARSER_NODE_KEYWORD,
    0,
    "switch",
    NULL,
    &cparser_node_version_root_unswitch,
    &cparser_node_version_root_switch_eol
};

cparser_node_t cparser_node_version_root_query_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version_query,
    "query version",
    NULL,
    NULL
};

cparser_node_t cparser_node_version_root_query = {
    CPARSER_NODE_KEYWORD,
    0,
    "query",
    NULL,
    &cparser_node_version_root_switch,
    &cparser_node_version_root_query_eol
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord,
    "download version [ftp|tftp] [app|system] VersionName ServerIP Port {UserName PassWord}",
    NULL,
    NULL
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:PassWord>",
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord_eol
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_version_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord,
    NULL
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "<STRING:UserName>",
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_eol
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_version_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName_PassWord,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_UserName,
    NULL
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:Port>",
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port_eol
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP = {
    CPARSER_NODE_IPV4ADDR,
    0,
    "<IPV4ADDR:ServerIP>",
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP_Port
};

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType_VersionName = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:VersionName>",
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName_ServerIP
};

cparser_list_node_t cparser_list_node_version_root_download_version_ServerType_VersionType_system = {
    NULL,
    "system"
 };

cparser_list_node_t cparser_list_node_version_root_download_version_ServerType_VersionType_app = {
    &cparser_list_node_version_root_download_version_ServerType_VersionType_system,
    "app"
 };

cparser_node_t cparser_node_version_root_download_version_ServerType_VersionType = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_version_root_download_version_ServerType_VersionType_app,
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType_VersionName
};

cparser_list_node_t cparser_list_node_version_root_download_version_ServerType_tftp = {
    NULL,
    "tftp"
 };

cparser_list_node_t cparser_list_node_version_root_download_version_ServerType_ftp = {
    &cparser_list_node_version_root_download_version_ServerType_tftp,
    "ftp"
 };

cparser_node_t cparser_node_version_root_download_version_ServerType = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_version_root_download_version_ServerType_ftp,
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType_VersionType
};

cparser_node_t cparser_node_version_root_download_version = {
    CPARSER_NODE_KEYWORD,
    0,
    "version",
    NULL,
    NULL,
    &cparser_node_version_root_download_version_ServerType
};

cparser_node_t cparser_node_version_root_download = {
    CPARSER_NODE_KEYWORD,
    0,
    "download",
    NULL,
    &cparser_node_version_root_query,
    &cparser_node_version_root_download_version
};

cparser_node_t cparser_node_version_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version_exit,
    "Exit version submode",
    NULL,
    NULL
};

cparser_node_t cparser_node_version_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    &cparser_node_version_root_download,
    &cparser_node_version_root_exit_eol
};

cparser_node_t cparser_node_version_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode version",
    NULL,
    &cparser_node_version_root_exit
};

cparser_node_t cparser_node_version_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_version,
    "version management",
    NULL,
    &cparser_node_version_root
};

cparser_node_t cparser_node_version = {
    CPARSER_NODE_KEYWORD,
    0,
    "version",
    NULL,
    &cparser_node_diagnose,
    &cparser_node_version_eol
};

cparser_node_t cparser_node_config_root_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_config_root_help_filter_eol
};

cparser_node_t cparser_node_config_root_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_config_help_filter,
    NULL,
    &cparser_node_config_root_help_filter,
    NULL
};

cparser_node_t cparser_node_config_root_help = {
    CPARSER_NODE_KEYWORD,
    0,
    "help",
    NULL,
    NULL,
    &cparser_node_config_root_help_eol
};

cparser_node_t cparser_node_config_root_reset_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_reset,
    "reset the reader",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_reset = {
    CPARSER_NODE_KEYWORD,
    0,
    "reset",
    NULL,
    &cparser_node_config_root_help,
    &cparser_node_config_root_reset_eol
};

cparser_node_t cparser_node_config_root_restore_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_restore,
    "restore factory default",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_restore = {
    CPARSER_NODE_KEYWORD,
    0,
    "restore",
    NULL,
    &cparser_node_config_root_reset,
    &cparser_node_config_root_restore_eol
};

cparser_node_t cparser_node_config_root_save_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_save,
    "save config",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_save = {
    CPARSER_NODE_KEYWORD,
    0,
    "save",
    NULL,
    &cparser_node_config_root_restore,
    &cparser_node_config_root_save_eol
};

cparser_node_t cparser_node_config_root_set_key_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_set_key_value,
    "set config the value type can be number,bool,string,such as \" set file.ntp.* 123456|true|\"str\" \"",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_set_key_value = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:value>",
    NULL,
    NULL,
    &cparser_node_config_root_set_key_value_eol
};

cparser_node_t cparser_node_config_root_set_key = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:key>",
    NULL,
    NULL,
    &cparser_node_config_root_set_key_value
};

cparser_node_t cparser_node_config_root_set = {
    CPARSER_NODE_KEYWORD,
    0,
    "set",
    NULL,
    &cparser_node_config_root_save,
    &cparser_node_config_root_set_key
};

cparser_node_t cparser_node_config_root_get_key_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_get_key,
    "get config",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_get_key = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:key>",
    NULL,
    NULL,
    &cparser_node_config_root_get_key_eol
};

cparser_node_t cparser_node_config_root_get = {
    CPARSER_NODE_KEYWORD,
    0,
    "get",
    NULL,
    &cparser_node_config_root_set,
    &cparser_node_config_root_get_key
};

cparser_node_t cparser_node_config_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_exit,
    "Exit config submode",
    NULL,
    NULL
};

cparser_node_t cparser_node_config_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    &cparser_node_config_root_get,
    &cparser_node_config_root_exit_eol
};

cparser_node_t cparser_node_config_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode config",
    NULL,
    &cparser_node_config_root_exit
};

cparser_node_t cparser_node_config_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config,
    "config management",
    NULL,
    &cparser_node_config_root
};

cparser_node_t cparser_node_config = {
    CPARSER_NODE_KEYWORD,
    0,
    "config",
    NULL,
    &cparser_node_version,
    &cparser_node_config_eol
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_config
};

